CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


DROP TABLE IF EXISTS (
  user_permission, 
  user_account, 
  party,
  user_party,
  movie,
  movie_party,
  party_order
);


CREATE TABLE user_account (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(128) NOT NULL,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(512) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
  activated BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER TABLE user_account ADD CONSTRAINT uk_user_account_email UNIQUE (email);


CREATE TABLE user_permission (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  role VARCHAR(128) CHECK (role IN ('USER', 'MODERATOR', 'ADMIN')) NOT NULL,
  user_id UUID NOT NULL
);
ALTER TABLE user_permission ADD CONSTRAINT uk_user_permission_role_user_id UNIQUE (role, user_id);
ALTER TABLE user_permission ADD CONSTRAINT fk_user_permission_user FOREIGN KEY (user_id) REFERENCES user_account(id);


CREATE TABLE party (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
  owner UUID NOT NULL
);
ALTER TABLE party ADD CONSTRAINT fk_party_user FOREIGN KEY (owner) REFERENCES user_account(id);


CREATE TABLE user_party (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  party_id UUID NOT NULL,
  user_id UUID NOT NULL,
  is_moderator BOOLEAN NOT NULL
);
ALTER TABLE user_party ADD CONSTRAINT pk_user_party PRIMARY KEY (id);
ALTER TABLE user_party ADD CONSTRAINT fk_user_party_party FOREIGN KEY (party_id) REFERENCES party(id);
ALTER TABLE user_party ADD CONSTRAINT fk_user_party_user FOREIGN KEY (user_id) REFERENCES user_account(id);
ALTER TABLE user_party ADD CONSTRAINT uk_user_party_user UNIQUE (party_id, user_id);


CREATE TABLE movie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(128) NOT NULL
);
ALTER TABLE movie ADD CONSTRAINT pk_movie PRIMARY KEY (id);
ALTER TABLE movie ADD CONSTRAINT uk_movie_name UNIQUE (id, name);


CREATE TABLE movie_party (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  party_id UUID NOT NULL,
  movie_id BIGINT NOT NULL,
  was_watched BOOLEAN NOT NULL,
  was_approved BOOLEAN NOT NULL,
  linkedAt TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE movie_party ADD CONSTRAINT pk_movie_party PRIMARY KEY (id);
ALTER TABLE movie_party ADD CONSTRAINT uk_movie_party_party_movie UNIQUE (party_id, movie_id);
ALTER TABLE movie_party ADD CONSTRAINT fk_movie_party_party FOREIGN KEY (party_id) REFERENCES party(id);
ALTER TABLE movie_party ADD CONSTRAINT fk_movie_party_movie FOREIGN KEY (movie_id) REFERENCES movie(id);


CREATE TABLE party_order (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  party_id UUID NOT NULL,
  user_id UUID NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE party_order ADD CONSTRAINT fk_party_order_party FOREIGN KEY (party_id) REFERENCES party(id);
ALTER TABLE party_order ADD CONSTRAINT fk_party_order_user FOREIGN KEY (user_id) REFERENCES user_account(id);
ALTER TABLE party_order ADD CONSTRAINT uk_party_order_user UNIQUE (party_id, user_id);
